const TYPES = {
    MUserInfoRepository: Symbol.for("MUserInfoRepository"),
    SignUpUseCaseInputPort: Symbol.for("SignUpUseCaseInputPort"),
    MUserInfoUseCaseInputPort: Symbol.for("MUserInfoUseCaseInputPort"),
    LoginUseCaseInputPort: Symbol.for("LoginUseCaseInputPort"),
    AxiosInitSetting: Symbol.for("AxiosInitSetting"),
    LoginManager: Symbol.for("LoginManager"),
    TermsConditionsRepository: Symbol.for("TermsConditionsRepository"),
    TermsConditionsUseCaseInputPort: Symbol.for("TermsConditionsUseCaseInputPort"),
    NoticeRepository: Symbol.for("NoticeRepository"),
    NoticeUseCaseInputPort: Symbol.for("NoticeUseCaseInputPort"),
    EventManagementRepository: Symbol.for("EventManagementRepository"),
    EventManagementUseCaseInputPort: Symbol.for("EventManagementUseCaseInputPort"),
    EventManagementListTableStatue: Symbol.for("EventManagementListTableStatue"),
    MaliciousBallRepository: Symbol.for("MaliciousBallRepository"),
    MaliciousBallUseCaseInputPort: Symbol.for("MaliciousBallUseCaseInputPort"),
    FBallRepository: Symbol.for("FBallRepository"),
    FBallUseCaseInputPort: Symbol.for("FBallUseCaseInputPort"),
    MaliciousBallPageListTableStatue: Symbol.for("MaliciousBallPageListTableStatue"),
    FBallDescriptionConverterInputPort: Symbol.for("FBallDescriptionConverterInputPort"),
    MaliciousBallJudgementUseCaseFactory: Symbol.for("MaliciousBallJudgementUseCaseFactory"),
    MaliciousProfileRepository: Symbol.for("MaliciousProfileRepository"),
    MaliciousProfileUseCaseInputPort: Symbol.for("MaliciousProfileUseCaseInputPort"),
    MaliciousProfileJudgementUseCaseFactory: Symbol.for("MaliciousProfileJudgementUseCaseFactory"),
    MaliciousProfilePageListTableStatue: Symbol.for("MaliciousProfilePageListTableStatue"),
    FUserInfoRepository: Symbol.for("FUserInfoRepository"),
    FUserInfoUseCaseInputPort: Symbol.for("FUserInfoUseCaseInputPort"),
    MaliciousReplyRepository: Symbol.for("MaliciousReplyRepository"),
    MaliciousReplyUseCaseInputPort: Symbol.for("MaliciousReplyUseCaseInputPort"),
    MaliciousReplyJudgementUseCaseFactory: Symbol.for("MaliciousReplyJudgementUseCaseFactory"),
    MaliciousReplyPageListTableStatus: Symbol.for("MaliciousReplyPageListTableStatus"),
    FBallReplyRepository: Symbol.for("FBallReplyRepository"),
    FBallReplyUseCaseInputPort: Symbol.for("FBallReplyUseCaseInputPort")
}
export default TYPES;